spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev    #开发环境
  application:
    name:microservicecloud-config-orient-dev
---
spring:
  profiles: test    #测试环境
  application:
    name: microservicecloud-config-orient-test
#请切记一定要保存为UTF-8的格式
        