spring:
  profiles:
    active:
    - dev
---
server:
  port: 8001
spring:
  profiles: dev
  application:
    name:microservicecloud-config-dept-client
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://locahost:3306/dbcloud_8001
    username: root
    password: superff
    minIdle: 5
    maxActive: 100
    initialSize: 10
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 50
    removeAbandoned: true
    filters: stat # ,wall,log4j # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000 # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    useGlobalDataSourceStat: true # 合并多个DruidDataSource的监控数据
    druidLoginName: wjf # 登录druid的账号
    druidPassword: wjf # 登录druid的密码
    cachePrepStmts: true # 开启二级缓存
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml   #mybatis配置文件的地址
  type-aliases-package:  com.orient.entities.Dept
  mapper-locations: classpath:mybatis/mapper/**/*.xml
eureka:
  client:
    service-url:
      #defaultZone:  http://localhost:7001/eureka    #将客户端注册到eureka中
      defaultZone:  http://eureka7001.com:7001/eureka
  instance:
    instance-id:  dept-8001.com  #默认服务名称的修改
    prefer-ip-address: true  #访问路径可以显示ip地址
    
info:
  app.name: orient-mocroservicecloud-springcloudconfig02
  company.name: www.orient.com
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}
---